### ISSUE TITLE
 Err(Other(ClientImport("Execution: Trap: Trap { kind: Unreachable }")))

### ISSUE THREAD

**Issue by PavelSheremetev** [airalab/robonomics#58] opened 2020-07-05 12:49 UTC
when the node of the parachain crashes ( commit de37f9f5514827556d05a308300d8e1cba250fde ), the following errors periodically appear:
<details>
  <summary>Click to expand</summary>
Jul 05 12:31:40 node-02 robonomics[122525]: 2020-07-05 12:31:40 panicked at 'Storage root must match that calculated.', /rustc/16957bd4d3a5377263f76ed74c572aad8e4b7e59/src/libcore/macros/mod.rs:10:9
Jul 05 12:31:40 node-02 robonomics[122525]: 2020-07-05 12:31:40 Block prepare storage changes error:
Jul 05 12:31:40 node-02 robonomics[122525]: Execution(Wasmi(Trap(Trap { kind: Unreachable })))
Jul 05 12:31:40 node-02 robonomics[122525]: 2020-07-05 12:31:40 💔 Error importing block 0x280bd22487c08eb9a02802f993d18f1fbace6b963d2a428c1ef283b75ee7b518: Err(Other(ClientImport("Execution: Trap: Trap { kind: Unreachable }")))
Jul 05 12:31:42 node-02 robonomics[122525]: 2020-07-05 12:31:42 ✨ [Relaychain] Imported #887 (0xe55c…50ff)
Jul 05 12:31:42 node-02 robonomics[122525]: 2020-07-05 12:31:42 Starting parachain attestation session on top of parent 0xe55cd3a2966bb1e138b482681ef410d43a00d4eeadfdc3b91f03c2d0ff8550ff. Local parachain duty is None
Jul 05 12:31:43 node-02 robonomics[122525]: 2020-07-05 12:31:43 ⚙️  [Parachain] Syncing  0.0 bps, target=#593 (27 peers), best: #541 (0x6072…7e8d), finalized #541 (0x6072…7e8d), ⬇ 5.5kiB/s ⬆ 3.7kiB/s
Jul 05 12:31:43 node-02 robonomics[122525]: Hash: given=9d9fb6e86f04c3e39f42e28b6e5cd29ec63256e9e942d8b6ce779d8675ed12bb, expected=147a18ca49aa976c9fe4597fde215fd5a4c1f3a2329c700adbade6da8366de67
Jul 05 12:31:43 node-02 robonomics[122525]: ====================
Jul 05 12:31:43 node-02 robonomics[122525]: Version: 0.18.3-de37f9f-x86_64-linux-gnu
Jul 05 12:31:43 node-02 robonomics[122525]:    0: sp_panic_handler::set::{{closure}}
Jul 05 12:31:43 node-02 robonomics[122525]:    1: std::panicking::rust_panic_with_hook
Jul 05 12:31:43 node-02 robonomics[122525]:              at /rustc/9912925c254589f58338cb2993163e618475ff75/src/libstd/panicking.rs:481
Jul 05 12:31:43 node-02 robonomics[122525]:    2: std::panicking::begin_panic
Jul 05 12:31:43 node-02 robonomics[122525]:    3: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_block
Jul 05 12:31:43 node-02 robonomics[122525]:    4: <robonomics_parachain_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<pallet_indices::Module<robonomics_parachain_runtime::Runtime> as sp_runtime::traits::StaticLookup>::Source,robonomics_parachain_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<robonomics_parachain_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<robonomics_parachain_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<robonomics_parachain_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<robonomics_parachain_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<robonomics_parachain_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<robonomics_parachain_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<robonomics_parachain_runtime::Runtime>)>>>>::execute_block
Jul 05 12:31:43 node-02 robonomics[122525]:    5: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
Jul 05 12:31:43 node-02 robonomics[122525]:    6: std::thread::local::LocalKey<T>::with
Jul 05 12:31:43 node-02 robonomics[122525]:    7: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
Jul 05 12:31:43 node-02 robonomics[122525]:    8: sc_executor::wasm_runtime::RuntimeCache::with_instance
Jul 05 12:31:43 node-02 robonomics[122525]:    9: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
Jul 05 12:31:43 node-02 robonomics[122525]:   10: sp_state_machine::StateMachine<B,H,N,Exec>::execute_aux
Jul 05 12:31:43 node-02 robonomics[122525]:   11: sp_state_machine::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
Jul 05 12:31:43 node-02 robonomics[122525]:   12: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
Jul 05 12:31:43 node-02 robonomics[122525]:   13: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Jul 05 12:31:43 node-02 robonomics[122525]:   14: sp_api::runtime_decl_for_Core::execute_block_call_api_at
Jul 05 12:31:43 node-02 robonomics[122525]:   15: sp_api::Core::execute_block_with_context
Jul 05 12:31:43 node-02 robonomics[122525]:   16: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
Jul 05 12:31:43 node-02 robonomics[122525]:   17: <alloc::sync::Arc<T> as sp_consensus::block_import::BlockImport<B>>::import_block
Jul 05 12:31:43 node-02 robonomics[122525]:   18: sp_consensus::import_queue::import_single_block_metered
Jul 05 12:31:43 node-02 robonomics[122525]:   19: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Jul 05 12:31:43 node-02 robonomics[122525]:   20: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
Jul 05 12:31:43 node-02 robonomics[122525]:   21: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
Jul 05 12:31:43 node-02 robonomics[122525]:   22: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Jul 05 12:31:43 node-02 robonomics[122525]:   23: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Jul 05 12:31:43 node-02 robonomics[122525]:   24: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Jul 05 12:31:43 node-02 robonomics[122525]:   25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jul 05 12:31:43 node-02 robonomics[122525]:   26: std::thread::local::LocalKey<T>::with
Jul 05 12:31:43 node-02 robonomics[122525]:   27: futures_executor::local_pool::block_on
Jul 05 12:31:43 node-02 robonomics[122525]:   28: tokio::runtime::task::core::Core<T,S>::poll
Jul 05 12:31:43 node-02 robonomics[122525]:   29: tokio::runtime::task::raw::poll
Jul 05 12:31:43 node-02 robonomics[122525]:   30: tokio::runtime::blocking::pool::Inner::run
Jul 05 12:31:43 node-02 robonomics[122525]:   31: tokio::runtime::context::enter
Jul 05 12:31:43 node-02 robonomics[122525]:   32: std::sys_common::backtrace::__rust_begin_short_backtrace
Jul 05 12:31:43 node-02 robonomics[122525]:   33: core::ops::function::FnOnce::call_once{{vtable.shim}}
Jul 05 12:31:43 node-02 robonomics[122525]:   34: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Jul 05 12:31:43 node-02 robonomics[122525]:              at /rustc/9912925c254589f58338cb2993163e618475ff75/src/liballoc/boxed.rs:1034
Jul 05 12:31:43 node-02 robonomics[122525]:       <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Jul 05 12:31:43 node-02 robonomics[122525]:              at /rustc/9912925c254589f58338cb2993163e618475ff75/src/liballoc/boxed.rs:1034
Jul 05 12:31:43 node-02 robonomics[122525]:       std::sys::unix::thread::Thread::new::thread_start
Jul 05 12:31:43 node-02 robonomics[122525]:              at /rustc/9912925c254589f58338cb2993163e618475ff75/src/libstd/sys/unix/thread.rs:87
Jul 05 12:31:43 node-02 robonomics[122525]:   35: start_thread
Jul 05 12:31:43 node-02 robonomics[122525]:   36: clone
Jul 05 12:31:43 node-02 robonomics[122525]: Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:13
Jul 05 12:31:43 node-02 robonomics[122525]: This is a bug. Please report it at:
Jul 05 12:31:43 node-02 robonomics[122525]:         https://github.com/airalab/robonomics/issues/new
</details>

**Comment by PavelSheremetev** [comment] 2020-07-30 15:32
robonomics 0.19.0-aec541a-x86_64-linux-gnu
`

> Jul 30 15:23:33 node-01 robonomics[1790303]: Hash: given=a06efed5c9659eaded3bc791f2f4cef6204b6336c68f4a194e8cfdbb6a6e6666, expected=802e7f5f5e8284148f8d355468e4ae33609e143d6e6704f8eea8e7ef50cd2d78
> Jul 30 15:23:33 node-01 robonomics[1790303]: ====================
> Jul 30 15:23:33 node-01 robonomics[1790303]: Version: 0.19.0-aec541a-x86_64-linux-gnu
> Jul 30 15:23:33 node-01 robonomics[1790303]:    0: sp_panic_handler::set::{{closure}}
> Jul 30 15:23:33 node-01 robonomics[1790303]:    1: std::panicking::rust_panic_with_hook
> Jul 30 15:23:33 node-01 robonomics[1790303]:              at /rustc/9912925c254589f58338cb2993163e618475ff75/src/libstd/panicking.rs:481
> Jul 30 15:23:33 node-01 robonomics[1790303]:    2: std::panicking::begin_panic
> Jul 30 15:23:33 node-01 robonomics[1790303]:    3: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_block
> Jul 30 15:23:33 node-01 robonomics[1790303]:    4: <robonomics_parachain_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<pallet_indices::Module<robonomics_parachain_runtime::Runtime> as sp_runtime::traits::StaticLookup>::Source,robonomics_parachain_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<robonomics_parachain_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<robonomics_parachain_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<robonomics_parachain_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<robonomics_parachain_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<robonomics_parachain_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<robonomics_parachain_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<robonomics_parachain_runtime::Runtime>)>>>>::execute_block
> Jul 30 15:23:33 node-01 robonomics[1790303]:    5: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
> Jul 30 15:23:33 node-01 robonomics[1790303]:    6: std::thread::local::LocalKey<T>::with
> Jul 30 15:23:33 node-01 robonomics[1790303]:    7: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
> Jul 30 15:23:33 node-01 robonomics[1790303]:    8: sc_executor::wasm_runtime::RuntimeCache::with_instance
> Jul 30 15:23:33 node-01 robonomics[1790303]:    9: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
> Jul 30 15:23:33 node-01 robonomics[1790303]:   10: sp_state_machine::StateMachine<B,H,N,Exec>::execute_aux
> Jul 30 15:23:33 node-01 robonomics[1790303]:   11: sp_state_machine::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
> Jul 30 15:23:33 node-01 robonomics[1790303]:   12: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
> Jul 30 15:23:33 node-01 robonomics[1790303]:   13: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
> Jul 30 15:23:33 node-01 robonomics[1790303]:   14: sp_api::Core::execute_block_with_context
> Jul 30 15:23:33 node-01 robonomics[1790303]:   15: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
> Jul 30 15:23:33 node-01 robonomics[1790303]:   16: <alloc::sync::Arc<T> as sp_consensus::block_import::BlockImport<B>>::import_block
> Jul 30 15:23:33 node-01 robonomics[1790303]:   17: sp_consensus::import_queue::import_single_block_metered
> Jul 30 15:23:33 node-01 robonomics[1790303]:   18: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
> Jul 30 15:23:33 node-01 robonomics[1790303]:   19: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
> Jul 30 15:23:33 node-01 robonomics[1790303]:   20: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
> Jul 30 15:23:33 node-01 robonomics[1790303]:   21: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
> Jul 30 15:23:33 node-01 robonomics[1790303]:   22: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
> Jul 30 15:23:33 node-01 robonomics[1790303]:   23: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
> Jul 30 15:23:33 node-01 robonomics[1790303]:   24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
> Jul 30 15:23:33 node-01 robonomics[1790303]:   25: std::thread::local::LocalKey<T>::with
> Jul 30 15:23:33 node-01 robonomics[1790303]:   26: futures_executor::local_pool::block_on
> Jul 30 15:23:33 node-01 robonomics[1790303]:   27: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
> Jul 30 15:23:33 node-01 robonomics[1790303]:   28: tokio::runtime::task::core::Core<T,S>::poll
> Jul 30 15:23:33 node-01 robonomics[1790303]:   29: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
> Jul 30 15:23:33 node-01 robonomics[1790303]:   30: tokio::runtime::task::raw::poll
> Jul 30 15:23:33 node-01 robonomics[1790303]:   31: tokio::runtime::blocking::pool::Inner::run
> Jul 30 15:23:33 node-01 robonomics[1790303]:   32: tokio::runtime::context::enter
> Jul 30 15:23:33 node-01 robonomics[1790303]:   33: std::sys_common::backtrace::__rust_begin_short_backtrace
> Jul 30 15:23:33 node-01 robonomics[1790303]:   34: core::ops::function::FnOnce::call_once{{vtable.shim}}
> Jul 30 15:23:33 node-01 robonomics[1790303]:   35: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
> Jul 30 15:23:33 node-01 robonomics[1790303]:              at /rustc/9912925c254589f58338cb2993163e618475ff75/src/liballoc/boxed.rs:1034
> Jul 30 15:23:33 node-01 robonomics[1790303]:       <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
> Jul 30 15:23:33 node-01 robonomics[1790303]:              at /rustc/9912925c254589f58338cb2993163e618475ff75/src/liballoc/boxed.rs:1034
> Jul 30 15:23:33 node-01 robonomics[1790303]:       std::sys::unix::thread::Thread::new::thread_start
> Jul 30 15:23:33 node-01 robonomics[1790303]:              at /rustc/9912925c254589f58338cb2993163e618475ff75/src/libstd/sys/unix/thread.rs:87
> Jul 30 15:23:33 node-01 robonomics[1790303]:   36: start_thread
> Jul 30 15:23:33 node-01 robonomics[1790303]:   37: clone
> Jul 30 15:23:33 node-01 robonomics[1790303]: Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:13
> Jul 30 15:23:33 node-01 robonomics[1790303]: This is a bug. Please report it at:
> Jul 30 15:23:33 node-01 robonomics[1790303]:         https://github.com/airalab/robonomics/issues/new
> Jul 30 15:23:33 node-01 robonomics[1790303]: 2020-07-30 15:23:33 panicked at 'Storage root must match that calculated.', /rustc/d7f94516345a36ddfcd68cbdf1df835d356795c3/src/libcore/macros/mod.rs:10:9
> Jul 30 15:23:33 node-01 robonomics[1790303]: 2020-07-30 15:23:33 Block prepare storage changes error:
> Jul 30 15:23:33 node-01 robonomics[1790303]: Execution(Wasmi(Trap(Trap { kind: Unreachable })))
> Jul 30 15:23:33 node-01 robonomics[1790303]: 2020-07-30 15:23:33 💔 Error importing block 0xd0ac0adc3d5527818088f5e996d5e15dca8f7c0ea233434a199d92cfb6c40108: Err(Other(ClientImport("Execution: Trap: Trap { kind: Unreachable }")))

`

**Comment by akru** [comment] 2020-08-01 00:39
Duplicate of https://github.com/airalab/robonomics/issues/60

**Closed by akru** 2020-08-01 00:39 UTC
